### PR TITLE
Making code more elegant and responsive

### LINKED ISSUE #35: Fake issue - Code refactoring
Lorem ipsum dolor sit amet

### LINKED ISSUE #43: Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

### PR DESCRIPTION
**Pull request by TestingKeypup**
Fixed bug error...
Fixes #35 
Fixes https://github.com/KeypDemoCorp/awesome-ui/issues/43
Fixes https://keypupqa.atlassian.net/browse/FPFT-3
Fixes https://keypupqa.atlassian.net/browse/FPFT-29
Fixes https://keypupqa.atlassian.net/browse/FPFT-30

### CODE REVIEW

**Review by tomazernour — APPROVED** [review]

**Comment by tomazernour** [comment]
Fixes https://keypupqa.atlassian.net/browse/FPFT-29

**Comment by tomazernour** [comment]
Fixes https://keypupqa.atlassian.net/browse/FPFT-30

**Comment by pixernot** [comment]
Some comment to delete

**Comment by tomazernour** [comment]
Test comment

**Pull request merged**
